# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.milkain.com:
    container_name: orderer.milkain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/milkain.com/orderers/orderer.milkain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/milkain.com/orderers/orderer.milkain.com/tls/:/var/hyperledger/orderer/tls
        - orderer.milkain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.manufacturer.milkain.com:
    container_name: peer0.manufacturer.milkain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.manufacturer.milkain.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.milkain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manufacturer.milkain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.milkain.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/manufacturer.milkain.com/peers/peer0.manufacturer.milkain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/manufacturer.milkain.com/peers/peer0.manufacturer.milkain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.manufacturer.milkain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.consumer.milkain.com:
    container_name: peer0.consumer.milkain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.consumer.milkain.com
      - CORE_PEER_ADDRESS=peer0.consumer.milkain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.milkain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.milkain.com:9051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.milkain.com/peers/peer0.consumer.milkain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.milkain.com/peers/peer0.consumer.milkain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.consumer.milkain.com:/var/hyperledger/production
    ports:
      - 9051:9051
